meltwater/drone-cache

.drone.yml, cache/backend/backend.go, plugin/plugin_test.go
=> Fix tag trigger issues

.drone.yml, .goreleaser.yml, Dockerfile
This PR unifies release stage of binary by including docker images to goreleaser
=> Goreleaser releases Docker images

README.md
Update README future work section to hint future contributors what's on the road map.
=> Update README.md, future work

CHANGELOG.md
- Update the CHANGELOG.md with prior releases
=> ChangeLog updates

docs/examples/drone-0.8.md, docs/examples/drone-1.0.md
Fixes #40
- Fix Filesystem/Volume example
- Add a note regarding usage with multiple agents
=> Fix Filesystem/Volume example

.github/CODEOWNERS
Further CODEOWNERS that can help to review PRs would be great. So let's add some :)
Adding Kai (limayekaiwalya) and Sean (seandtaber) as GitHUB codeowners.
=> adding Kai (limayekaiwalya) and Sean (seandtaber) as GitHUB codeowners

docs/examples/drone-0.8.md
Fixes #81
- fix indentation in example for drone 0.8
fix indentation in example for drone 0.8
=> Fix indentation in example for drone 0.8

.drone.yml
=> Specify pull behaviour for CI

docs/examples/drone-0.8.md, docs/examples/drone-1.0.md
Fixes #92
- Fix the links to a right location
Fix the links to a right location
=> Fix broken link in docs

Makefile
Fixes #101 
Tried to upgrade makefile without changing functionality.  Is this version fix your problem?
=> Makefile upgrades

README.md
Forgot to updated cli args in README
=> Update docs for CLI args with new override flag

.github/workflows/release.yaml, .github/workflows/snapshot.yaml, .goreleaser-snapshot.yml
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
Fixes #122
- Add `goreleser-snapshot.yaml` to separate snapshot build pipeline.
- Modify concerning github action.
- Upgrades `goreleaser`
As reported in https://github.com/meltwater/drone-cache/issues/122, we ha
=> Push images for snapshots

.drone.yml
Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>
Changes are not relevant to end user.
=> Use latest release candidate in CI

CHANGELOG.md, main.go
Fixes #135.
Fixes parsing of GCS JSON key argument/envvar.
=> Fix typo in parsing of GCS JSON key

.github/CODEOWNERS
Hey :wave: 
As the title clearly indicates I'm stepping down as a maintainer. Sadly I have no spare time or interest to continue maintain the project. It's been a while since I last used the `drone-cache` as well as `drone` itself. It's unfair to contributors since I seem to be the reviewer and I get pinged on the issues and pull requests, yet I rarely can have a look at them. I would be glad if someone who has more passion to maintain the project to take it over.
Thanks for everything.
Cheers
=> Stepping down as the maintainer

README.md
As a follow-up to #161 I am suggesting to add @kakkoyun to the 'Authors and Acknowledgement' section ❤️
=> [docs] Adding kakkoyun to the 'Authors and Acknowledgement' section

.github/workflows/release.yaml, .github/workflows/snapshot.yaml
=> Fix release

.github/workflows/snapshot.yaml
=> Fix snapshot process

.github/workflows/release.yaml
Fixes #
* Fix tags for release process
-
-
-
We do not want release.yaml to run when a tag with release candidate is been pushed.
=> Fix release process tags

.drone-local.yml, .drone.yml, .goreleaser-local.yml, CHANGELOG.md, CONTRIBUTING.md
Fixes #99
- Added a new Goreleaser yaml that only builds the image locally without attempting to publish to Dockerhub
- Created a separate Drone pipeline that can be when running drone locally
- Did the above, and added relevant entries to the changelog and CONTRIBUTING.MD
=> ATEAM-10574 update docs for local testing

.goreleaser-snapshot.yml
Fixes #
- Adding arm64 support to goreleaser snapshot to build arm64 docker image
=> adding arm64 to goreleaser snapshot

.goreleaser-snapshot.yml
my mistake, goarch doesn't take a list, the builds have to be separate
Fixes #
-
-
-
=> separate arm64 docker build

.github/workflows/snapshot.yaml, .goreleaser-snapshot.yml
updating goreleaser should make this work
Fixes #
-
-
-
=> arm64 goreleaser snapshot

.github/workflows/snapshot.yaml
these actions should allow for arm docker image builds
Fixes #
-
-
-
=> add buildx actions

.drone.yml
this will test the latest release candidate in our pipeline steps
=> update .drone.yml to use v1.2.0-rc1

.github/workflows/release.yaml, .goreleaser-snapshot.yml, .goreleaser.yml, CHANGELOG.md
updating github actions
updating goreleaser
removing latest tag from goreleaser-snapshot that was added by mistake
doing my best to update/fix the changelog
=> preparing to release 1.2.0

CONTRIBUTING.md
=> Ateam 11370 update drone cache doc

CHANGELOG.md, README.md
- Finalized CHANGELOG for v1.4.0 release
- Fixed examples in README
=> 1-4-0_stage fixed the README and set the CHANGELOG for v1.4.0

CHANGELOG.md
- Fix date and name for v1.4.0 in CHANGELOG
=> noticket_fix1.4.0 fixed the CHANGELOG for v1.4.0

.github/workflows/release.yaml
- Fixes [goreleaser](https://github.com/meltwater/drone-cache/runs/8144521907?check_suite_focus=true)
=> bump go version for goreleaser

.github/workflows/release.yaml
- Fixes [goreleaser](https://github.com/meltwater/drone-cache/runs/8144777587?check_suite_focus=true) _try 2_
=> bump go version for goreleaser: try 2

CHANGELOG.md
- Changelog cleanup for v1.4.0 release
Changelog cleanup for v1.4.0 release
=> Stage for v1.4.0 release

.drone-local.yml, .drone.yml, CHANGELOG.md, README.md, internal/plugin/plugin_test.go, main.go, storage/backend/s3/config.go, storage/backend/s3/s3.go, storage/backend/s3/s3_test.go
Please read [CONTRIBUTING.md](/CONTRIBUTING.md) for details on our [code of conduct](/CODE_OF_CONDUCT.md), and the process for submitting pull requests to us.
Fixes #
- Added a command line flag to enable or disable SSL for AWS s3 buckets.
- Updated testing for AWS s3 backend module to support SSL.
- Updated README file to reflect the changes.
- Added a function (method) on s3 backend (in file `s3.go`) to switch SSL mode based on command line flag (default is false).
- Added variable `DisableSSL` to s3 backend config.
-  Disable SSL in test files `plugin_test.go and s3_test.go` to support Minio storage for testing (Mino https is not enabled yet).
- Modified `main.go` file to have the new SSL flag available on the command line.
- Updated README.md and CHANGELOG.md to reflect the changes …
=> [ATEAM-13065]: Adding command line flag for SSL for AWS s3
