- README.md
A quick update to the plain Docker example: clarifying that the folder that the user wants to cache has to also be mounted onto the Docker container.
> Fix pure Docker example in Readme

- DOCS.md
- README.md
- docs/cache_key_templates.md
- main.go
- metadata/metadata.go
It appears that `$DRONE_REPO_OWNER` has been renamed to `$DRONE_REPO_NAMESPACE`: https://docs.drone.io/reference/environ/drone-repo-namespace/
This PR removes the CLI flag `--repo.owner` and replaces it with `--repo.namespace`, and adds a `Namespace` field to the `Repo` definition. It preserves the `Owner` field for backwards-compatibility, which is filled out using the value from `$DRONE_REPO_NAMESPACE` / `--repo.namespace`.
> Rename DRONE_REPO_OWNER to DRONE_REPO_NAMESPACE

- README.md
Implements #64. I removed the Future Work changes from the README.
I modified or created new issues for these:
- Add s/FTP Backend 
- Add [Google Cloud Storage Backend](https://cloud.google.com/storage/) 
- Add [Azure Storage Backend](https://azure.microsoft.com/en-in/services/storage/)
- Add [Alibaba OSS Backend](https://www.alibabacloud.com/product/oss) 
@kakkoyun I don't have enough context to write stories for the 4 topics below. Can you please create issues for these or decide what to do with them otherwise?
- Flush or TTL/Retention policy 
- Fix goreleaser/drone/docker conflicts or remove redundancy with Drone jsonnet
- Add cache key fallback list
- Add unit tests
> [docs] move Future Work to issues

- .drone.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTING.md
Fixes #69 
- Removes `release-latest` stage from CI's master merge pipeline.
- Updates and improves contributing guidelines.
This PR introduces changes to ensure backwards compatibility and guarantee not to introduce breaking changes prevent auto releasing of `latest` tag when a merge happens on `master`. Since `latest` is used default image for most of the pipelines.
> Update guidelines and Stop pushing docker images with latest tag when master merge happens

- .drone.yml
- CHANGELOG.md
- main.go
This PR adds a new parameter to API to ensure plugin fails for any type of error.
This is a hidden convenience flag to test the plugin in a container.
Fixes #58 
- Adds `--exit-code` flag
- Fixes duplicate flag error introduced by #68 changes
- Adds a new pipeline step to the drone flow, to dogfood our own pipeline.
- This PR adds a new parameter to API to ensure plugin fails for any type of error.
This is a hidden convenience flag to test the plugin in a container.
> Add exit code flag

- docker-compose.yml
They don't seem to be used in tests anyway and without them removed `make test` does fail for me localy
> Remove unneeded test service volumes

- CHANGELOG.md
- DOCS.md
- cache/cache.go
- cache/option.go
- cache/rebuilder.go
- internal/plugin/config.go
- internal/plugin/plugin.go
- internal/plugin/plugin_test.go
- main.go
- storage/backend/azure/azure.go
- storage/backend/azure/azure_test.go
- storage/backend/backend.go
- storage/backend/filesystem/filesystem.go
- storage/backend/filesystem/filesystem_test.go
- storage/backend/gcs/gcs.go
- storage/backend/gcs/gcs_test.go
- storage/backend/s3/s3.go
- storage/backend/s3/s3_test.go
- storage/backend/sftp/sftp.go
- storage/backend/sftp/sftp_test.go
- storage/storage.go
Adds `override` option that is true by default to preserve backward compatibility
Fixes #83
> Implement option to disable cache rebuild if it already exists in storage

- archive/tar/tar.go
- archive/tar/tar_test.go
Current code while cleaning up path would trim `.` (dot) character. 
Fixes #105
> Fix relative path resolving to not trim dot char

- Makefile
- README.md
This ain't a biggie but I was trying to fix a little formatting problem in the README.
However not sure if my change has the desired effect?
Here the thing that I am trying to fix:
- minor formatting issue in the README
> Removing leading newline in code block

- .drone.yml
- .goreleaser.yml
- DOCS.md
- Dockerfile
- README.md
- docs/examples/drone.md
Update master with release branch changes.
> Merge release v1.1

- CHANGELOG.md
- README.md
- storage/backend/s3/s3.go
Fixes [#132](https://github.com/meltwater/drone-cache/issues/132)
> Fix NoCredentialProviders error when accessing public bucket on Minio

- CHANGELOG.md
- storage/backend/gcs/gcs.go
Fixes #137 by not overriding the HTTP client when not necessary.
Without this, GCS errors with 403:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
```
This happens when `GCS_ENDPOINT` isn't set, and the Google SDK is called with `option.WithHTTPClient()` using a custom HTTP client that disables TLS verification.
> Fix GCS credentials when no endpoint specified

- .drone.yml
- CHANGELOG.md
- README.md
- docker-compose.yml
- main.go
- storage/backend/s3/config.go
- storage/backend/s3/s3.go
- storage/backend/s3/s3_test.go
Fixes #142
- add flag to specify role arn
- if role arn is specified, use access keys to assume the role with arn provided
Allows specifying role ARN which, if specified, is assumed with STS. All S3 operations are executed with this role.
> Add optional param for AWS IAM role assumption

- .goreleaser.yml
- set goarch for arm64 goreleaser
- docker image was published with a amd64 binary because this was not set
> set goarch for arm64 goreleaser

- CHANGELOG.md
- README.md
- main.go
- storage/backend/s3/config.go
- storage/backend/s3/s3.go
Fixes #188 
Add optional ` s3_bucket_public` setting to use anonymous credentials when accessing public S3 buckets.
> Only use anon credentials for public s3 buckets

- .github/PULL_REQUEST_TEMPLATE.md
Fixing broken links in pull request template
> [skip ci] fix pr template links

- README.md
Without forcing the value to be interpreted as a string, the `{` bracket starts a new object block, and gives the following failure from drone:
```
yaml: invalid map key: map[interface {}]interface {}{"checksum \"yarn.lock\"":interface {}(nil)}
```
> [SKIP CI] Wrap `cache_key` in single-quotes in docs

- .github/CODEOWNERS
General update of CODEOWNERS to reflect latest project ownership. No CI validation needed.
> [skip ci] Update CODEOWNERS for 2022 onwards

- CHANGELOG.md
- README.md
- go.mod
- go.sum
- internal/plugin/config.go
- internal/plugin/plugin.go
- main.go
- storage/backend/alioss/alioss.go
- storage/backend/alioss/alioss_test.go
- storage/backend/alioss/config.go
- storage/backend/backend.go
- storage/backend/config.go
Please read [CONTRIBUTING.md](/CONTRIBUTING.md) for details on our [code of conduct](/CODE_OF_CONDUCT.md), and the process for submitting pull requests to us.
Fixes [#65] (https://github.com/meltwater/drone-cache/issues/65) Add Alibaba OSS Storage Backend
Is your feature request related to a problem? Please describe.
As a user of the [Alibaba Cloud](https://www.alibabacloud.com/), I want to use [Alibaba OSS Storage](https://www.alibabacloud.com/product/oss) to persist my cache, so that I can reuse the storage system that I already know.
Describe the solution you'd like
Alibaba OSS Storage Backend
Describe alternatives you've considered
using a separate storage backend that already exists in drone-cache
Additional context
none
- Implemented Alibaba OSS backend storage for caching
- Updated …
> [ATEAM-13094]: Implement Alibaba OSS backend

- CHANGELOG.md
- archive/tar/tar.go
Fixes #210
- First, archive/tar now uses PAX tar format which allows for sub-second resolutions (https://pkg.go.dev/archive/tar#Format). This only affects rebuild's, so previosly built archive will not be broken. 
- And then extracting files, it sets times if file header container modification time.
- Please not that only files' timestamps are currently restored, not directories'.
In line with the liked issue, currently restored files (when using filesystem backend) do not preserve original timestamps, which leads to some build systems to rebuild. This PR fixes that.
> Restore file modification times

- go.mod
- go.sum
This fixes the issues with `go-ieproxy` on release builds, namely [this](https://github.com/meltwater/drone-cache/actions/runs/2974890604) issue
> [skip ci] bump go-ieproxy to fix darwin goreleaser builds

- .github/workflows/release.yaml
No change to source, just trying to fix automation to build the releases correctly due to old issues with `go-ieproxy`
> [skip ci] bump goreleaser and action to attempt to fix releases

- .goreleaser.yml
- go.sum
Fixes #218
- Fix goreleaser by disabling Windows builds due to `mattn/go-ieproxy` build issues (see https://github.com/mattn/go-ieproxy/pull/44 for possible fix)
Goreleaser fails building for any Windows architecture due to issues with an upstream dependency. It seems in the past we disable failing platforms, even if we want to support them, as this allows us to go forward whilst the upstream dependencies tackle the relevant issues.
N/A due to CI and release process fixes unrelated to application code.
> ATEAM-13324 Fix goreleaser builds for v1.4.0
